apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: agent-service
  ports:
    - port: {{ .Values.agent.port }}
      targetPort: {{ .Values.agent.port }}

